name: depup
on:
  schedule:
    - cron:  '0 2,14 * * *'
  workflow_dispatch:

jobs:
  reviewdog-litestream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-depup/with-pr@v1.4.12
        with:
          file: Dockerfile
          version_name: LITESTREAM_IMAGE_TAG
          repo: benbjohnson/litestream
          tag: true

  reviewdog-memos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-depup/with-pr@v1.4.12
        with:
          file: Dockerfile
          version_name: MEMOS_IMAGE_TAG
          repo: usememos/memos
          tag: true

  reviewdog-memogram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-depup/with-pr@v1.4.12
        with:
          file: Dockerfile
          version_name: MEMOGRAM_TAG
          repo: usememos/telegram-integration
          tag: true
